version: '2'
services:
  geth:
    image: daocloud.io/daocloud/geth
    restart: on-failure
    environment:
      - WS_SERVER ws://blockchain.daocloud.io:80
      - WS_SECRET daocloud-eth-net-stats-secret
      - NODES=enode://34fd75df3e84b709e7712138fc7c2be8adf46c005d26dd5579dcf3f6d75bef44fd492f4fe726460145d66b5f6dc964edad1bc290fdd6bb26fe757fff33d62386@106.75.14.2:30303
    volumes:
      - /root/.ethereum/keystore
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  server:
    image: daocloud.io/alphabeta_com/hub-blockchain
    restart: on-failure
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "8000:80"
